[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_color_term=111
    let g:indentLine_color_gui='#708090'
    let g:indentLine_char='|'
'''



