[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_color_term=111
    let g:indentLine_color_gui='#708090'
    let g:indentLine_char='|'
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_sign_column_always = 1
    " time to check
    let g:ale_lint_on_enter = 1
    let g:ale_lint_on_save  = 1
    let g:ale_lint_on_text_changed = 'never'
    " error and warning signal
    let g:ale_sign_error   = 'E'
    let g:ale_sign_warning = 'W'
    " message format
    let g:ale_echo_msg_error_str   = 'E'
    let g:ale_echo_msg_warning_str = 'W'
    let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
    " always show error column
    let g:ale_sign_column_always = 1
    " location list and QuickFix
    let g:ale_set_loclist = 1
    let g:ale_set_quickfix = 0
    " open window to list of errors and warnings
    let g:ale_open_list = 0
    let g:ale_keep_list_window_open = 0
    let g:ale_list_window_size = 5
    " linters
    let g:ale_linters = {'python': ['flake8']}
    let g:ale_linters = {'cpp': ['clang']}
'''

